branches:
  - main
  - staging:
      prerelease: rc
      channel: rc

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - 
    path: "@semantic-release/exec"
    successCmd: |
      # Update version in __version__.py
      sed -i "s/^__version__ = .*/__version__ = '{{nextRelease.version}}'/" codeshieldapp/__version__.py

      # Update version in pyproject.toml
      sed -i "s/^version = .*/version = \"{{nextRelease.version}}\"/" pyproject.toml

  - 
    path: "@semantic-release/git"
    assets:
      - "CHANGELOG.md"
      - "pyproject.toml"
      - "codeshieldapp/__version__.py"
    message: "chore(release): {{nextRelease.version}} [skip ci]\n\n{{nextRelease.notes}}"

  - 
    path: "@semantic-release/github"
    assets:
      - "CHANGELOG.md"
      - "pyproject.toml"
      - "codeshieldapp/__version__.py"
    releaseName: "{{nextRelease.version}}"
    prerelease: true