branches:
  - main
  - staging:
      prerelease: rc
      channel: rc

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - 
    path: "@semantic-release/exec"
    prepareCmd: |
        # Check if on staging branch and append -rc to the version if true
        if [[ "${GITHUB_REF}" == "refs/heads/staging" ]]; then
          version="${nextRelease.version}-rc"
        else
          version="${nextRelease.version}"
        fi

        # Update __version__.py with the version
        sed --in-place 's/__version__ = ".*"/__version__ = "'${version}'"/' codeshieldapp/__version__.py

        # Update pyproject.toml with the version
        sed --in-place 's/version = ".*"/version = "'${version}'"/' pyproject.toml

        # Update poetry lock file and version
        poetry lock --no-update
        poetry version ${version}
  - 
    path: "@semantic-release/git"
    assets:
      - "CHANGELOG.md"
      - "pyproject.toml"
      - "codeshieldapp/__version__.py"
    message: "chore(release): ${nextRelease.version}-rc [skip ci]\n\n${nextRelease.notes}"