branches:
  - main
  - staging:
      prerelease: rc
      channel: rc

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - 
    path: "@semantic-release/exec"
    prepareCmd: |
        sed --in-place 's/__version__ = ".*"/__version__ = "${nextRelease.version}"/' codeshieldapp/__version__.py
        poetry lock --no-update
        poetry version ${nextRelease.version}
  - 
    path: "@semantic-release/git"
    assets:
      - "CHANGELOG.md"
      - "pyproject.toml"
      - "codeshieldapp/__version__.py"
    message: "chore(release): ${nextRelease.version}-rc [skip ci]\n\n${nextRelease.notes}"