apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeshield-app
  labels:
    app: codeshield-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codeshield-app
  template:
    metadata:
      labels:
        app: codeshield-app
    spec:
      containers:
        - name: codeshield-app
          image: env-rbnfrhnrtest-registry.jcloud.ik-server.com/codeshield-app:v1
          ports:
            - containerPort: 8000