apiVersion: v1
kind: Service
metadata:
  name: codeshield-app-service
spec:
  type: LoadBalancer
  selector:
    app: codeshield-app
  ports:
    - protocol: TCP
      port: 30085
      targetPort: 8000