apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeshield-app
  labels:
    app: codeshield-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeshield-app
  template:
    metadata:
      labels:
        app: codeshield-app
    spec:
      containers:
        - name: codeshield-app
          image: env-rbnfrhnrtest-registry.jcloud.ik-server.com/codeshield-app:latest-rc
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          env:
            - name: CFG_FILE
              value: "/app/config.yaml"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: app-config
